### ISSUE TITLE
Sample code won't compile?

### ISSUE THREAD

**Issue by tdsteve** [CosmosOS/Cosmos#187]
Trying to build a Cosmos C# project without modifying the sample code at all throws this error:

1>------ Build started: Project: CosmosKernel1, Configuration: Debug Any CPU ------
1>  CosmosKernel1 -> c:\users\[omitted]\documents\visual studio 2013\Projects\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1.dll
2>------ Build started: Project: CosmosKernel1Boot, Configuration: Debug x86 ------
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error : Exception: System.NullReferenceException: Object reference not set to an instance of an object.
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(SymbolFormat symFormat, String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 133
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 106
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 99
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(String aAsmPathname, Int32 aMethodToken, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 231
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(MethodBase aMethod, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 226
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.AppAssembler.MethodBegin(MethodInfo aMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 167
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 462
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 929
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 251
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Message: Executing IL2CPU on assembly
2>	Message: Plug found: 'Microsoft.Win32.RegistryKey'
2>	Message: Plug found: 'System.Array'
2>	Message: Plug found: 'System.Byte'
2>	Message: Plug found: 'System.Char'
2>	Message: Plug found: 'System.Delegate'
2>	Message: Plug found: 'System.Double'
2>	Message: Plug found: 'System.Drawing.Color'
2>	Message: Plug found: 'System.Drawing.SR'
2>	Message: Plug found: 'System.Enum'
2>	Message: Plug found: 'System.Environment'
2>	Message: Plug found: 'System.GC'
2>	Message: Plug found: 'System.Globalization.CultureInfo'
2>	Message: Plug found: 'System.Globalization.NumberFormatInfo'
2>	Message: Plug found: 'System.Int16'
2>	Message: Plug found: 'System.Int32'
2>	Message: Plug found: 'System.Int64'
2>	Message: Plug found: 'System.IntPtr'
2>	Message: Plug found: 'System.Net.IPAddress'
2>	Message: Plug found: 'System.Net.SocketAddress'
2>	Message: Plug found: 'System.Number'
2>	Message: Plug found: 'System.Object'
2>	Message: Plug found: 'System.Resources.ResourceManager'
2>	Message: Plug found: 'System.RuntimeType'
2>	Message: Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>	Message: Plug found: 'System.RuntimeTypeHandle'
2>	Message: Plug found: 'System.Security.CodeAccessSecurityEngine'
2>	Message: Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>	Message: Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>	Message: Plug found: 'System.SByte'
2>	Message: Plug found: 'System.Security.Cryptography.Utils'
2>	Message: Plug found: 'System.Single'
2>	Message: Plug found: 'System.SR'
2>	Message: Plug found: 'System.String'
2>	Message: Plug found: 'System.Threading.Interlocked'
2>	Message: Plug found: 'System.UInt16'
2>	Message: Plug found: 'System.UInt32'
2>	Message: Plug found: 'System.UInt64'
2>	Message: Plug found: 'System.Diagnostics.Debugger'
2>	Message: Plug found: 'System.Math'
2>	Message: Plug found: 'System.Buffer'
2>	Message: Plug found: 'System.EventHandler'
2>	Message: Plug found: 'System.Exception'
2>	Message: Plug found: 'System.MulticastDelegate'
2>	Message: Plug found: 'System.OutOfMemoryException'
2>	Message: Plug found: 'Cosmos.Core.CPU'
2>	Message: Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>	Message: Plug found: 'Cosmos.Core.IOPortBase'
2>	Message: Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>	Message: Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>	Message: Plug found: 'System.Random'
2>	Message: Plug found: 'System.Text.DecoderFallback'
2>	Message: Plug found: 'System.Text.EncoderFallback'
2>	Message: Plug found: 'System.Text.ASCIIEncoding'
2>	Message: Plug found: 'System.Console'
2>	Message: Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>	Message: Plug found: 'System.Threading.Monitor'
2>	Message: Plug found: 'System.Type'
2>	Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
2>	Message: Loaded assemblies: 
2>	Message: C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	Message: c:\users\[omitted]\documents\visual studio 2013\Projects\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSharp.Nasm.dll
2>	Message: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	Message: C:\Users\[omitted]\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\corapi.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:02.1199734
2>Done building project "CosmosKernel1Boot.Cosmos" -- FAILED.
2>
2>Build FAILED.
Build has been canceled.

I'm using VS 2013, VMware and .NET are installed per the instructions. Really hope this can be solved quickly, I need this library for a project very soon.

**Comment by mterwoord** [comment]
Can you try to update the reference from the .cosmos project to the c# project?

**Comment by stevethedude** [comment]
Keep in mind, I'm a complete noob to this, I just started learning. How would I do that?

**Comment by zdimension** [comment]
Well, what you need to do is to go in the Solution Explorer, expand the project called CosmosKernel1Boot (if it's not already expanded) expand References, click on CosmosKernel1 (under references) and press Del. Then right click on References, click Add Reference, click on Projects and then on CosmosKernel1. Then try to build again.

**Comment by stevethedude** [comment]
Nope, same error. "Error occurred while invoking IL2CPU"

**Comment by mterwoord** [comment]
Still same il2cpu error? (ie, in output window)

**Comment by stevethedude** [comment]
Mhm. @zdimension even compiled the devkit for me, same result.

**Comment by stevethedude** [comment]
Error confirmed in both C# and VB.NET projects.

**Comment by mterwoord** [comment]
So, according to gitter chat, this issue is resolved? If so, please let us know here how you did that, and close this issue. Thanks.

**Comment by stevethedude** [comment]
Nope, issue not resolved. Just used a different machine for compiling.

**Comment by mterwoord** [comment]
If you can, please try to use the code we use to access pdb information, to see if it also doesn't work in an isolated test.

An option would be to try to convert to http://www.nuget.org/packages/Microsoft.DiaSymReader.Native/1.1.0-alpha1

Not sure if it works for us, but at least worth a try, I'd say...

**Comment by FreddyD-GH** [comment]
I was just playing around with a clean VS2015 install and I encountered a very similar error that seemed to come from the line:
`NativeMethods.CoCreateInstance(ref dispenserClassID, null, 1, ref dispenserIID, out objDispenser);`
in SymAccess.cs

It appears this call has some sort of dependency on .NET 3.5/2.0 being installed.  Once I installed, it seemed to work as expected.  Maybe @stevethedude could confirm if that's the issue for him too?

**Comment by mterwoord** [comment]
If that's the case, maybe someone could give a look at the Microsoft.DiaSymReader.Native package ? See if that one works without? 

@FreddyD-GH Thanks for looking into this! :)

**Comment by mmkhmmkh** [comment]
Just Install .NET 3.5 !

**Comment by mterwoord** [comment]
@stevethedude Does this solve things?

**Comment by Fireflies** [comment]
Can confirm installing 3.5 worked for me.

**Comment by mterwoord** [comment]
Thanks for confirming!

**Comment by mterwoord** [comment]
Issue opened, #218

**Comment by Irxori-TheBetrayed** [comment]
@tdsteve 
Hey, even though you've probably solved this by now, I would go install Bochs instead of VMWare. It worked for me. Once Bochs is installed, right click on CosmosKernel1 and click properties. Then click Bochs and close the window. Press F5, then it should work.

**Comment by mterwoord** [comment]
@Irxori-TheBetrayed The problem this issue is about has nothing to do with running. Our compiler relies on some COM objects which are only installed on .net 3.5....

**Comment by Fireflies** [comment]
Vote to lock conversation to collabs.

**Comment by charlesbetros** [comment]
What's the problem?

**Comment by Linecommander** [comment]
**solved!**
The problem is, that visual studio doesn't have the required compiler to run the project.
**Solution**
Install a virtual machine software (im using Vmware workstation)
Debug and boom working!

**Comment by CSharpandLua** [comment]
Same error i have .NET 3.5, VMware and every solution here, i never changed anything either!
