### ISSUE TITLE
Crash on Console.ReadKey()

### ISSUE THREAD

**Issue by AndyKolski** [CosmosOS/Cosmos#375]
If Console.ReadKey() is used, when a key is pressed the OS will crash with various CPU exceptions mainly x0D or x06.
The error can be reproduced with "ConsoleKeyInfo key = Console.ReadKey();".

**Comment by charlesbetros** [comment]
This should be fixed in the latest master.

**Comment by AndyKolski** [comment]
I have just downloaded and installed the latest version of COSMOS and the bug is still there.

**Comment by mterwoord** [comment]
What key are you pressing?

**Comment by AndyKolski** [comment]
Any key will cause the crash.

**Comment by mterwoord** [comment]
This is in latest versino of Cosmos? Ie, devkit?

**Comment by AndyKolski** [comment]
I am using the User Kit.

**Comment by mterwoord** [comment]
It's fixed in devkit.

**Comment by AndyKolski** [comment]
OK, Great!

**Comment by LosSkillos** [comment]
Why is this issue still in the devkit?

**Comment by Project-Magenta** [comment]
user kit versions are not pushed a lot. normally you can use the dev kit for bugfixes

**Comment by charlesbetros** [comment]
I'd you are still experiencing this issue on the latest master feel free to fix it and submit a pull-request rather than complain. :)

If you would like help with submitting code to Cosmos we are happy to guide you.

**Comment by fy1vo51** [comment]
I founded a solution for how to press a key without being crashed the CPU at debugging!

Here's the code that I made:
![cosmosc#_pause](https://user-images.githubusercontent.com/63316499/89740170-74359c80-da54-11ea-8a59-56ca35e6b5ce.png)


I hope it work just for you guys!

**Comment by fy1vo51** [comment]
Use this instead:
![cosmosc#_pause](https://user-images.githubusercontent.com/63316499/89740254-16558480-da55-11ea-98c5-f638e622ba65.png)
